version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies..."
      - mvn clean install
  pre_build:
    commands:
      - echo "Pre-build phase..."
      - mvn validate
  build:
    commands:
      - echo "Building the application..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Post-build phase..."
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
    - target/social-media-blog-app-0.0.1-SNAPSHOT.jar
  discard-paths: yes
